version: "3.8"

services:
  api:
    container_name: 1640-web-enterprise
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1313:1313"
    volumes:
      - api:/usr/src/app/  
    depends_on:
      - 1640_postgres
    command: [ "/app/main" ]
    networks: 
      - 1640-web-enterprise


  1640_postgres:
    image: postgres:14-alpine
    container_name: 1640_postgesql
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=1640
    volumes:
      - postgres-db:/var/lib/postgresql/data  
    networks: 
      - 1640-web-enterprise


volumes:
  postgres-db:
  api:
networks:
  1640-web-enterprise:
    driver: bridge