// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: comment.sql

package db

import (
	"context"
	"time"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments(
    id, 
    content,   
    is_anonymous, 
    user_id,
    idea_id,
    created_at
) VALUES (
    $1,  $2,  $3, $4, $5, $6
)
RETURNING id, content, is_anonymous, user_id, idea_id, created_at
`

type CreateCommentParams struct {
	ID          string    `json:"id"`
	Content     string    `json:"content"`
	IsAnonymous bool      `json:"is_anonymous"`
	UserID      string    `json:"user_id"`
	IdeaID      string    `json:"idea_id"`
	CreatedAt   time.Time `json:"created_at"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, createComment,
		arg.ID,
		arg.Content,
		arg.IsAnonymous,
		arg.UserID,
		arg.IdeaID,
		arg.CreatedAt,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.IsAnonymous,
		&i.UserID,
		&i.IdeaID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments
WHERE id = $1
    RETURNING id, content, is_anonymous, user_id, idea_id, created_at
`

func (q *Queries) DeleteComment(ctx context.Context, id string) (Comment, error) {
	row := q.db.QueryRowContext(ctx, deleteComment, id)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.IsAnonymous,
		&i.UserID,
		&i.IdeaID,
		&i.CreatedAt,
	)
	return i, err
}

const getCommentsByIdea = `-- name: GetCommentsByIdea :many
Select comments.id, comments.content, comments.is_anonymous, comments.user_id, comments.idea_id, comments.created_at, users.avatar, users.username
FROM comments
         INNER JOIN users ON comments.user_id = users.id
WHERE idea_id = $1
`

type GetCommentsByIdeaRow struct {
	ID          string    `json:"id"`
	Content     string    `json:"content"`
	IsAnonymous bool      `json:"is_anonymous"`
	UserID      string    `json:"user_id"`
	IdeaID      string    `json:"idea_id"`
	CreatedAt   time.Time `json:"created_at"`
	Avatar      string    `json:"avatar"`
	Username    string    `json:"username"`
}

func (q *Queries) GetCommentsByIdea(ctx context.Context, ideaID string) ([]GetCommentsByIdeaRow, error) {
	rows, err := q.db.QueryContext(ctx, getCommentsByIdea, ideaID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCommentsByIdeaRow
	for rows.Next() {
		var i GetCommentsByIdeaRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.IsAnonymous,
			&i.UserID,
			&i.IdeaID,
			&i.CreatedAt,
			&i.Avatar,
			&i.Username,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $1,
    is_anonymous = $2
WHERE id = $3
    RETURNING id, content, is_anonymous, user_id, idea_id, created_at
`

type UpdateCommentParams struct {
	Content     string `json:"content"`
	IsAnonymous bool   `json:"is_anonymous"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRowContext(ctx, updateComment, arg.Content, arg.IsAnonymous, arg.ID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.IsAnonymous,
		&i.UserID,
		&i.IdeaID,
		&i.CreatedAt,
	)
	return i, err
}
