// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: idea.sql

package db

import (
	"context"
	"time"
)

const createIdea = `-- name: CreateIdea :one
INSERT INTO ideas(
    id, 
    title, 
    content, 
    view_count, 
    document_array, 
    image_array, 
    upvote_count, 
    downvote_count, 
    is_anonymous, 
    user_id, 
    category_id, 
    academic_year, 
    created_at
) VALUES (
    $1,  $2,  $3,  $4, 
    CASE WHEN $5 = '' THEN 'null' ELSE $5 END, 
    CASE WHEN $6 = '' THEN 'null' ELSE $6 END,
    $7, $8, $9, $10, $11, $12, $13
)
RETURNING id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at
`

type CreateIdeaParams struct {
	ID            string      `json:"id"`
	Title         string      `json:"title"`
	Content       string      `json:"content"`
	ViewCount     int32       `json:"view_count"`
	Column5       interface{} `json:"column_5"`
	Column6       interface{} `json:"column_6"`
	UpvoteCount   int32       `json:"upvote_count"`
	DownvoteCount int32       `json:"downvote_count"`
	IsAnonymous   bool        `json:"is_anonymous"`
	UserID        string      `json:"user_id"`
	CategoryID    string      `json:"category_id"`
	AcademicYear  string      `json:"academic_year"`
	CreatedAt     time.Time   `json:"created_at"`
}

func (q *Queries) CreateIdea(ctx context.Context, arg CreateIdeaParams) (Idea, error) {
	row := q.db.QueryRowContext(ctx, createIdea,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.ViewCount,
		arg.Column5,
		arg.Column6,
		arg.UpvoteCount,
		arg.DownvoteCount,
		arg.IsAnonymous,
		arg.UserID,
		arg.CategoryID,
		arg.AcademicYear,
		arg.CreatedAt,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.DocumentArray,
		&i.ImageArray,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.IsAnonymous,
		&i.UserID,
		&i.CategoryID,
		&i.AcademicYear,
		&i.CreatedAt,
	)
	return i, err
}

const deleteIdea = `-- name: DeleteIdea :one
DELETE FROM ideas
WHERE id = $1
    RETURNING id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at
`

func (q *Queries) DeleteIdea(ctx context.Context, id string) (Idea, error) {
	row := q.db.QueryRowContext(ctx, deleteIdea, id)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.DocumentArray,
		&i.ImageArray,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.IsAnonymous,
		&i.UserID,
		&i.CategoryID,
		&i.AcademicYear,
		&i.CreatedAt,
	)
	return i, err
}

const getIdea = `-- name: GetIdea :one
SELECT id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at FROM ideas WHERE id=$1
`

func (q *Queries) GetIdea(ctx context.Context, id string) (Idea, error) {
	row := q.db.QueryRowContext(ctx, getIdea, id)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.DocumentArray,
		&i.ImageArray,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.IsAnonymous,
		&i.UserID,
		&i.CategoryID,
		&i.AcademicYear,
		&i.CreatedAt,
	)
	return i, err
}

const getIdeaByAcademicyear = `-- name: GetIdeaByAcademicyear :many
SELECT id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at FROM ideas WHERE academic_year = $1
LIMIT $2
OFFSET $3
`

type GetIdeaByAcademicyearParams struct {
	AcademicYear string `json:"academic_year"`
	Limit        int32  `json:"limit"`
	Offset       int32  `json:"offset"`
}

func (q *Queries) GetIdeaByAcademicyear(ctx context.Context, arg GetIdeaByAcademicyearParams) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, getIdeaByAcademicyear, arg.AcademicYear, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.DocumentArray,
			&i.ImageArray,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.IsAnonymous,
			&i.UserID,
			&i.CategoryID,
			&i.AcademicYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIdeaByCategory = `-- name: GetIdeaByCategory :many
SELECT id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at FROM ideas WHERE category_id = $1
LIMIT $2
OFFSET $3
`

type GetIdeaByCategoryParams struct {
	CategoryID string `json:"category_id"`
	Limit      int32  `json:"limit"`
	Offset     int32  `json:"offset"`
}

func (q *Queries) GetIdeaByCategory(ctx context.Context, arg GetIdeaByCategoryParams) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, getIdeaByCategory, arg.CategoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.DocumentArray,
			&i.ImageArray,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.IsAnonymous,
			&i.UserID,
			&i.CategoryID,
			&i.AcademicYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestIdeas = `-- name: GetLatestIdeas :many
Select id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at FROM ideas ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type GetLatestIdeasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetLatestIdeas(ctx context.Context, arg GetLatestIdeasParams) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, getLatestIdeas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.DocumentArray,
			&i.ImageArray,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.IsAnonymous,
			&i.UserID,
			&i.CategoryID,
			&i.AcademicYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostPopularIdeas = `-- name: GetMostPopularIdeas :many
Select id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at FROM ideas ORDER BY upvote_count DESC
LIMIT $1
OFFSET $2
`

type GetMostPopularIdeasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetMostPopularIdeas(ctx context.Context, arg GetMostPopularIdeasParams) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, getMostPopularIdeas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.DocumentArray,
			&i.ImageArray,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.IsAnonymous,
			&i.UserID,
			&i.CategoryID,
			&i.AcademicYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostViewedIdeas = `-- name: GetMostViewedIdeas :many
Select id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at FROM ideas ORDER BY view_count DESC
LIMIT $1
OFFSET $2
`

type GetMostViewedIdeasParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetMostViewedIdeas(ctx context.Context, arg GetMostViewedIdeasParams) ([]Idea, error) {
	rows, err := q.db.QueryContext(ctx, getMostViewedIdeas, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Idea
	for rows.Next() {
		var i Idea
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.ViewCount,
			&i.DocumentArray,
			&i.ImageArray,
			&i.UpvoteCount,
			&i.DownvoteCount,
			&i.IsAnonymous,
			&i.UserID,
			&i.CategoryID,
			&i.AcademicYear,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNumberOfAllIdeas = `-- name: GetNumberOfAllIdeas :one
SELECT COUNT(*) 
FROM ideas
`

func (q *Queries) GetNumberOfAllIdeas(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberOfAllIdeas)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getNumberOfIdeasByDepartment = `-- name: GetNumberOfIdeasByDepartment :one
SELECT COUNT(*) 
FROM ideas
WHERE user_id IN (
    SELECT user_id 
    FROM users 
    WHERE department_id = $1
)
`

func (q *Queries) GetNumberOfIdeasByDepartment(ctx context.Context, departmentID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNumberOfIdeasByDepartment, departmentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateIdea = `-- name: UpdateIdea :one
UPDATE ideas
SET  title = $1,
    content = $2,
    document_array = $3,
    image_array = $4,
    is_anonymous = $5,
    academic_year = $6,
    category_id = $7
WHERE id = $8
    RETURNING id, title, content, view_count, document_array, image_array, upvote_count, downvote_count, is_anonymous, user_id, category_id, academic_year, created_at
`

type UpdateIdeaParams struct {
	Title         string         `json:"title"`
	Content       string         `json:"content"`
	DocumentArray string   		 `json:"document_array"`
	ImageArray    string 		 `json:"image_array"`
	IsAnonymous   bool           `json:"is_anonymous"`
	AcademicYear  string         `json:"academic_year"`
	CategoryID    string         `json:"category_id"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateIdea(ctx context.Context, arg UpdateIdeaParams) (Idea, error) {
	row := q.db.QueryRowContext(ctx, updateIdea,
		arg.Title,
		arg.Content,
		arg.DocumentArray,
		arg.ImageArray,
		arg.IsAnonymous,
		arg.AcademicYear,
		arg.CategoryID,
		arg.ID,
	)
	var i Idea
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.ViewCount,
		&i.DocumentArray,
		&i.ImageArray,
		&i.UpvoteCount,
		&i.DownvoteCount,
		&i.IsAnonymous,
		&i.UserID,
		&i.CategoryID,
		&i.AcademicYear,
		&i.CreatedAt,
	)
	return i, err
}
